### ISSUE TITLE
plans for 15 seconds in swift?

### ISSUE THREAD

**Issue by stanchiang** [tapharmonic/Learning-AV-Foundation-Swift#1]
any plans to port the 15 seconds project to swift? I'm going through your book and it would improve comprehension a lot if there was a swift code to work with.

**Comment by bobmccune** [comment]
The sample projects, including 15 Seconds, most likely won't be ported over to Swift until a second edition of the book. Some early discussions have happened regarding a 2nd edition, but there are no concrete plans at this time.
