### ISSUE TITLE
crash when loading longer MP3 files

### ISSUE THREAD

**Issue by masaldana2** [tapharmonic/Learning-AV-Foundation-Swift#2]
Hello for chapter 8,
I tried loading ~5 min - 45min mp3 files and it crashes when it tries to get the maximum value of the current bin.
it works great with 15 second files.

**Comment by bobmccune** [comment]
Thanks for the heads up. I'll look into it when I get a chance.

**Comment by bobmccune** [comment]
What device and OS are you running? I just loaded up an 9 minute plus mp3 file (23.8mb) on my 6s running iOS 10. It looks a while to load and render the file, but it ran fine for me.

**Comment by masaldana2** [comment]
I get that error running a on iphone 6 ios 10 
and same error with iphone 7 ios 11 beta
and ipad pro ios 11 beta . 
using xcode 9 new beta

tried xcode 8 and same err using iphone 6 ios10...

loading 8mb file
<img width="1433" alt="screen shot 2017-07-21 at 1 08 54 am" src="https://user-images.githubusercontent.com/7034219/28451160-378d2a4a-6db1-11e7-862f-939f6fb2fdea.png">
